baseURL: https://zemliany.github.io
languageCode: en-us
title: Blackhole
theme: mini
defaultContentLanguage: en
themesDir: themes
hasCJKLanguage: true
permalinks:
  posts: /posts/:title/
paginate: 3

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: false
    style: monokai
    lineNumbers: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

# Site parameters
params:
  author: Maksym Zemlianyi
  # Author biography
  bio: DevOps | SRE | Platform Engineer
  description: My Blog
  social:
    github: https://github.com/zemliany
    linkedin: https://www.linkedin.com/in/zemliany

  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  # enableRSS: true
  enableComments: true
  enableGoogleAnalytics: false
  showToc: true
  showPowerBy: true
  math: false
  hiddenPostSummaryInHomePage: false
  copyright: ''